language: node_js
node_js:
   - "6.*"
   - "5.*"
   - "4.*"
   - "4.*"
   - "0.12.*"

branches:
  only:
    - master

script:
    - "npm run test"

after_success:
    - SAUCELABS=true npm run test:browser

cache:
  directories:
    - node_modules

notifications:
    email: false

sudo: false
